In [3]:
import numpy as np
english_score = np.array([55,89,76,65,48,70])
math_score = np.array([60,85,60,68,np.nan,60])
math_score_no = np.array([60,85,60,68,60])
chinese_score = np.array([65,90,82,72,66,77])
math_score_no

array([60, 85, 60, 68, 60])

In [4]:
english_score

array([55, 89, 76, 65, 48, 70])

In [5]:
math_score

array([60., 85., 60., 68., nan, 60.])

In [6]:
chinese_score

array([65, 90, 82, 72, 66, 77])

In [7]:
np.amax(english_score)
print("english_score max：", np.amax(english_score))

english_score max： 89


In [8]:
np.amax(math_score_no)
print("math_score max：", np.amax(math_score_no))

math_score max： 85


In [9]:
np.amax(chinese_score)
print("chinese_score max：", np.amax(chinese_score))

chinese_score max： 90


In [10]:
np.amin(english_score)
print("english_score mun：", np.amin(english_score))

english_score mun： 48


In [11]:
np.amin(math_score_no)
print("math_score min：", np.amin(math_score_no))

math_score min： 60


In [12]:
np.amin(chinese_score)
print("chinese_score min：", np.amin(chinese_score))

chinese_score min： 65


In [13]:
np.mean(english_score)
print("english_score mean：", np.mean(english_score))

english_score mean： 67.16666666666667


In [14]:
if not np.isnan(np.sum(math_score)):
    print("陣列中無 nan，忽略 nan 後的平均值為：", np.mean(math_score))
else:
    print("陣列中有 nan，忽略 nan 後的平均值為：", np.nanmean(math_score))

陣列中有 nan，忽略 nan 後的平均值為： 66.6


In [15]:
np.mean(chinese_score)
print("chinese_score mean：", np.mean(chinese_score))

chinese_score mean： 75.33333333333333


In [16]:
np.std(english_score)
print("english_score sd：", np.std(english_score))

english_score sd： 13.433995020924426


In [17]:
np.nanstd(math_score)
print("陣列中有 nan，忽略 nan 後的sd為：：", np.nanstd(math_score))

陣列中有 nan，忽略 nan 後的sd為：： 9.707728879609279


In [18]:
np.std(chinese_score)
print("chinese_score sd：", np.std(chinese_score))

chinese_score sd： 8.825468196582484


In [19]:
math_score_re = np.array([60,85,60,68,55,60])
math_score_re

array([60, 85, 60, 68, 55, 60])

In [20]:
np.amax(math_score_re)

85

In [21]:
np.amin(math_score_re)

55

In [22]:
np.mean(math_score_re)

64.66666666666667

In [23]:
np.std(math_score_re)

9.860132971832694

In [27]:
np.correlate([65,90,82,72,66,77], [60,85,60,68,55,60])
print("chinese_score and math_score_re corr：", np.correlate(chinese_score, math_score_re))

chinese_score and math_score_re corr： [29616]


In [26]:
np.correlate(chinese_score, english_score)
print("chinese_score and english_score corr：", np.correlate(chinese_score, english_score))

chinese_score and english_score corr： [31055]


In [28]:
print("chinese_score and english_score corr is higher：", np.correlate(chinese_score, english_score))

chinese_score and english_score corr is higher： [31055]
